apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ai-manager
  labels:
    app: k8s-ai-manager
  annotations:
  # Image Updater가 모니터링할 이미지와 업데이트 전략 지정
    argocd-image-updater.argoproj.io/image-list: lkh8150/docker
    argocd-image-updater.argoproj.io/k8s-ai-manager.update-strategy: digest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ai-manager
  template:
    metadata:
      labels:
        app: k8s-ai-manager
    spec:
      containers:
        - name: k8s-ai-manager
          image: lkh8150/docker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: apiKey
